name: Collect

on:
  workflow_dispatch:
  schedule:
    # 06:00 JST (21: 00 UTC previous day)
    - cron: "0 21 * * *"
  push:
    branches:
      - main

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: k1LoW/octocov-action@v1
