name: Collect

on:
  workflow_dispatch:
  schedule:
    - cron: '17 15 * * *'
  push:
    branches:
      - main

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: k1LoW/octocov-action@v1
